//go:build integration

package fixtures

import (
	"os"
	"path/filepath"
	"testing"
)

// TestConfigPaths holds the generated configuration files for one test.
type TestConfigPaths struct {
	ConfigPath string
	RolePath   string
	EnvPath    string
	SoulPath   string
	SkillPath  string
	Workspace  string
}

// WriteTestConfig generates a minimal, isolated config set for integration
// tests. It points Postgres/Redis at the provided test database and the LLM at
// the provided mock base URL.
func WriteTestConfig(t testing.TB, db *TestDatabase, ws string, llmBaseURL string) *TestConfigPaths {
	t.Helper()
	dir := filepath.Join(ws, "config")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("create config dir: %v", err)
	}

	paths := &TestConfigPaths{
		ConfigPath: filepath.Join(dir, "config.yaml"),
		RolePath:   filepath.Join(dir, "roles.yaml"),
		EnvPath:    filepath.Join(dir, ".env"),
		SoulPath:   filepath.Join(dir, "soul.md"),
		SkillPath:  filepath.Join(dir, "skills.yaml"),
		Workspace:  ws,
	}

	writeFile(t, paths.ConfigPath, renderConfig(db.PostgresDSN, db.RedisAddr, db.RedisPass, db.RedisDB))
	writeFile(t, paths.RolePath, renderRoles())
	writeFile(t, paths.EnvPath, renderEnv(llmBaseURL))
	writeFile(t, paths.SoulPath, renderSoul())
	writeFile(t, paths.SkillPath, renderSkills())

	return paths
}

func writeFile(t testing.TB, path string, data []byte) {
	t.Helper()
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func renderConfig(postgresDSN, redisAddr, redisPass string, redisDB int) []byte {
	return []byte(`# Generated by integration test fixtures
postgres:
  dsn: "` + postgresDSN + `"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 300

pgvector:
  enabled: true
  dimensions: 768
  index_type: ivfflat
  distance_metric: cosine

redis:
  addr: "` + redisAddr + `"
  password: "` + redisPass + `"
  db: ` + itoa(redisDB) + `
  pool_size: 5
  min_idle_conns: 1
  dial_timeout: 5000
  read_timeout: 3000
  write_timeout: 3000
  snapshot_ttl_days: 1

http:
  addr: ":0"
  read_timeout: 30
  write_timeout: 30

memory:
  write_batch_size: 10
  write_flush_interval: 1
  snapshot_interval: 60

agent:
  stall_steps: 30
  max_repeat_fingerprint: 3
  session_timeout_min: 5
  skill_set_size: 4
  tool_call_max_rounds: 4
  retry_count: 1
  retry_backoff_ms: 10
  llm_soft_timeout_sec: 10
  llm_hard_timeout_sec: 20
  context_window: 8000
  interrupt_enabled: false
  queue_inject_enabled: false
  human_clarify_enabled: false
  dag_enabled: false
  plan_enabled: false
  reflection_enabled: false
  human_clarify_timeout_sec: 10

logging:
  enabled: false
  dir: logs
`)
}

func renderRoles() []byte {
	return []byte(`meta_agent:
  model_config:
    provider: openai
    model: mock-model
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}
    temperature: 0.3
    max_tokens: 2048
  system_prompt: |
    You are the MetaAgent. Keep answers short.
  max_blocks: 5
  summary_interval: 5

domain_agent:
  model_config:
    provider: openai
    model: mock-model
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}
    temperature: 0.5
    max_tokens: 4096

lightweight_model:
  provider: openai
  model: mock-model
  api_key: ${OPENAI_API_KEY}
  base_url: ${OPENAI_BASE_URL}
  temperature: 0.2
  max_tokens: 2048

fixed_roles:
  - id: code_assistant
    name: 代码助手
    type: fixed
    lifecycle: permanent
    description: 代码助手
    system_prompt: "You are a coding assistant."
    keywords: ["code", "bug"]
    skills: ["代码编写"]
    tools: ["ReadFile", "WriteFile", "RunCommand"]
    model_config:
      provider: openai
      model: mock-model
      api_key: ${OPENAI_API_KEY}
      base_url: ${OPENAI_BASE_URL}
      temperature: 0.4
      max_tokens: 4096
    can_be_called: true
    parents: []

  - id: ui_assistant
    name: UI助手
    type: fixed
    lifecycle: permanent
    description: UI助手
    system_prompt: "You are a UI assistant."
    keywords: ["UI", "CSS"]
    skills: ["UI修复"]
    tools: ["ReadFile", "WriteFile"]
    model_config:
      provider: openai
      model: mock-model
      api_key: ${OPENAI_API_KEY}
      base_url: ${OPENAI_BASE_URL}
      temperature: 0.5
      max_tokens: 4096
    can_be_called: true
    parents: []

dynamic_templates:
  - id: domain_template
    name: 领域负责人模板
    type: domain
    prompt_template: "You are the {domain} lead. Goal: {goal}"
    skills: []
    max_lifetime: 3600
  - id: assistant_template
    name: 临时助手模板
    type: assistant
    prompt_template: "You are an assistant for {task}."
    skills: []
    max_lifetime: 3600
`)
}

func renderEnv(llmBaseURL string) []byte {
	return []byte(`OPENAI_API_KEY=fake-api-key-for-tests
OPENAI_BASE_URL=` + llmBaseURL + `
`)
}

func renderSoul() []byte {
	return []byte(`你是一个多 Agent 编排助手。请简洁回答。`)
}

func renderSkills() []byte {
	return []byte(`skills:
  - skill_id: read_file
    name: 读取文件
    description: 读取本地文件并返回文本内容
    domain: code,doc,*
    tool_ref: ReadFile
    tags: [io, fs]

  - skill_id: write_file
    name: 写入文件
    description: 把文本内容写入本地文件
    domain: code,doc,*
    tool_ref: WriteFile
    tags: [io, fs]

  - skill_id: list_dir
    name: 列出目录
    description: 列出目录中的文件与子目录
    domain: code,*
    tool_ref: ListDir
    tags: [io, fs]

  - skill_id: search_in_files
    name: 代码搜索
    description: 在工作目录中按关键词搜索文件内容
    domain: code,doc,*
    tool_ref: SearchInFiles
    tags: [search]

  - skill_id: run_command
    name: 执行命令
    description: 在沙箱内执行 shell 命令并返回输出
    domain: code,ops,*
    tool_ref: RunCommand
    tags: [shell]

  - skill_id: http_get
    name: HTTP GET
    description: 对指定 URL 发起 GET 请求并返回 JSON/文本
    domain: ops,api,*
    tool_ref: HTTPGet
    tags: [http]

  - skill_id: http_post
    name: HTTP POST
    description: 对指定 URL 发起 POST 请求（带 JSON Body）
    domain: ops,api,*
    tool_ref: HTTPPost
    tags: [http]
`)
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	var buf [20]byte
	neg := false
	if i < 0 {
		neg = true
		i = -i
	}
	n := 0
	for i > 0 {
		buf[n] = byte('0' + i%10)
		i /= 10
		n++
	}
	if neg {
		buf[n] = '-'
		n++
	}
	for i := 0; i < n/2; i++ {
		buf[i], buf[n-1-i] = buf[n-1-i], buf[i]
	}
	return string(buf[:n])
}
